codecov:
  require_ci_to_pass: true

flag_management:
  default_rules:
    carryforward: true
    statuses:
      - type: project
        target: auto
        threshold: 1%
      - type: patch
        target: 90%
  individual_flags:
    - name: parser
      paths:
        - packages/parser/src/lib/**/*.ts
        - '!**/*.spec.ts'
